// Code generated by "stringer -type=ServerRole -output=string.go"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[main-1]
	_ = x[replica-2]
	_ = x[primary-3]
	_ = x[standby-4]
}

const _ServerRole_name = "mainreplicaprimarystandby"

var _ServerRole_index = [...]uint8{0, 4, 11, 18, 25}

func (i ServerRole) String() string {
	i -= 1
	if i >= ServerRole(len(_ServerRole_index)-1) {
		return "ServerRole(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ServerRole_name[_ServerRole_index[i]:_ServerRole_index[i+1]]
}
